version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: gdsc_advising_backend
    image: gdsc_advising-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env