name: Deploy frontend to Cloud Run

on:
    push:
        branches:
            - main # on push to main
            - feature/ci-cd # on testing for ci-cd
        paths:
            - frontend/**

jobs:
    deploy-fe:
        name: deploy-fe  
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend # change dir to frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env file
              run: touch .env
            
            - name: Update .env file with secrets
              run: |
                  echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> .env
                  echo "VITE_BACKEND_PORT=${{ secrets.VITE_BACKEND_PORT }}" >> .env
            
            - name: Verify .env file
              run: ls -l .env

            - name: Success
              run: echo "Success"
